"""Generate a sample 23andMe raw data file for testing."""

import json
from pathlib import Path

REFERENCE_DATA_DIR = Path(__file__).parent / "reference_data"
SAMPLE_DATA_DIR = Path(__file__).parent.parent / "sample-data"

SAMPLE_GENOTYPES = {
    "rs1801133": "CT",
    "rs1801131": "AC",
    "rs4680": "AG",
    "rs1799945": "CG",
    "rs1800562": "GA",
    "rs4988235": "CT",
    "rs12255372": "GT",
    "rs7903146": "CT",
    "rs9939609": "AT",
    "rs1042713": "AG",
    "rs662": "AG",
    "rs1800795": "GC",
    "rs53576": "AG",
    "rs429358": "CT",
    "rs7412": "CC",
    "rs1799853": "CT",
    "rs2228570": "CT",
    "rs731236": "TC",
    "rs1544410": "GA",
    "rs7041": "TG",
    "rs174547": "TC",
    "rs1800497": "AG",
    "rs4633": "CT",
    "rs6265": "CT",
    "rs1800544": "GC",
    "rs1799971": "AG",
    "rs28371706": "CC",
    "rs3892097": "GA",
    "rs776746": "AG",
    "rs4149056": "TC",
    "rs2032582": "GA",
    "rs1045642": "CT",
    "rs855791": "AG",
    "rs1800896": "AG",
    "rs1800629": "GA",
    "rs6311": "CT",
    "rs7775228": "CT",
    "rs10830963": "CG",
    "rs1801282": "CG",
    "rs8050136": "AC",
    "rs17782313": "TC",
    "rs1801394": "AG",
    "rs602662": "AG",
    "rs12934922": "AG",
    "rs7946": "CT",
    "rs234706": "GA",
    "rs1805087": "AG",
    "rs1799998": "AG",
    "rs4654748": "CT",
    "rs2060793": "AG",
}

CHROMOSOME_MAP = {
    "rs1801133": "1", "rs1801131": "1", "rs4680": "22", "rs1799945": "6",
    "rs1800562": "6", "rs4988235": "2", "rs12255372": "10", "rs7903146": "10",
    "rs9939609": "16", "rs1042713": "5", "rs662": "7", "rs1800795": "7",
    "rs53576": "3", "rs429358": "19", "rs7412": "19", "rs1799853": "10",
    "rs2228570": "12", "rs731236": "12", "rs1544410": "12", "rs7041": "4",
    "rs174547": "11", "rs1800497": "11", "rs4633": "22", "rs6265": "11",
    "rs1800544": "10", "rs1799971": "6", "rs28371706": "22", "rs3892097": "22",
    "rs776746": "7", "rs4149056": "12", "rs2032582": "7", "rs1045642": "7",
    "rs855791": "22", "rs1800896": "1", "rs1800629": "6", "rs6311": "13",
    "rs7775228": "6", "rs10830963": "11", "rs1801282": "3", "rs8050136": "16",
    "rs17782313": "18", "rs1801394": "5", "rs602662": "19", "rs12934922": "14",
    "rs7946": "17", "rs234706": "21", "rs1805087": "1", "rs1799998": "8",
    "rs4654748": "1", "rs2060793": "11",
}

POSITION_MAP = {
    "rs1801133": 11856378, "rs1801131": 11854476, "rs4680": 19963748,
    "rs1799945": 26091179, "rs1800562": 26093141, "rs4988235": 136608646,
    "rs12255372": 114808902, "rs7903146": 114758349, "rs9939609": 53820527,
    "rs1042713": 148206440, "rs662": 94937446, "rs1800795": 22766645,
    "rs53576": 8804371, "rs429358": 45411941, "rs7412": 45412079,
    "rs1799853": 96702047, "rs2228570": 48272895, "rs731236": 48238757,
    "rs1544410": 48239835, "rs7041": 72618334, "rs174547": 61570783,
    "rs1800497": 113400106, "rs4633": 19963684, "rs6265": 27679916,
    "rs1800544": 112837956, "rs1799971": 154360797, "rs28371706": 42127941,
    "rs3892097": 42130692, "rs776746": 99270539, "rs4149056": 21331549,
    "rs2032582": 87160618, "rs1045642": 87138645, "rs855791": 37462936,
    "rs1800896": 206946897, "rs1800629": 31575254, "rs6311": 47471478,
    "rs7775228": 32681631, "rs10830963": 92708710, "rs1801282": 12393125,
    "rs8050136": 53816275, "rs17782313": 60183864, "rs1801394": 7870860,
    "rs602662": 49206674, "rs12934922": 24609642, "rs7946": 17350235,
    "rs234706": 44485476, "rs1805087": 237048500, "rs1799998": 143953801,
    "rs4654748": 36099249, "rs2060793": 14913764,
}


def main():
    SAMPLE_DATA_DIR.mkdir(parents=True, exist_ok=True)

    with open(REFERENCE_DATA_DIR / "snp_database.json") as f:
        snp_db = json.load(f)

    output = SAMPLE_DATA_DIR / "sample_23andme.txt"
    with open(output, "w") as f:
        f.write("# This data file generated by 23andMe at: Thu May 15 12:00:00 2026\n")
        f.write("#\n")
        f.write("# Below is a text version of your data.\n")
        f.write("# Fields are TAB-separated.\n")
        f.write("# Each line corresponds to a single SNP.\n")
        f.write("#\n")
        f.write("# rsid\tchromosome\tposition\tgenotype\n")

        for rsid, genotype in SAMPLE_GENOTYPES.items():
            chrom = CHROMOSOME_MAP.get(rsid, "1")
            pos = POSITION_MAP.get(rsid, 10000000)
            f.write(f"{rsid}\t{chrom}\t{pos}\t{genotype}\n")

        for i in range(100):
            f.write(f"rs{90000000 + i}\t{(i % 22) + 1}\t{10000000 + i * 1000}\tAA\n")

    found = sum(1 for rsid in SAMPLE_GENOTYPES if rsid in snp_db)
    print(f"Generated {output}")
    print(f"Total SNPs: {len(SAMPLE_GENOTYPES) + 100}")
    print(f"Recognized by SNP database: {found}")


if __name__ == "__main__":
    main()
